// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK-RiDr0dNv9mpWVSJ8P19Gs2WIyYd_X8',
    appId: '1:39209386893:android:1a3c57e4be8e97ee89f3c4',
    messagingSenderId: '39209386893',
    projectId: 'fintech-80719',
    storageBucket: 'fintech-80719.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDigaXP7CdMykgZ3Y8xVdZcG73uW0PMJO4',
    appId: '1:39209386893:ios:161bef930fe8382b89f3c4',
    messagingSenderId: '39209386893',
    projectId: 'fintech-80719',
    storageBucket: 'fintech-80719.firebasestorage.app',
    iosBundleId: 'com.example.fintech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDigaXP7CdMykgZ3Y8xVdZcG73uW0PMJO4',
    appId: '1:39209386893:ios:161bef930fe8382b89f3c4',
    messagingSenderId: '39209386893',
    projectId: 'fintech-80719',
    storageBucket: 'fintech-80719.firebasestorage.app',
    iosBundleId: 'com.example.fintech',
  );

}